# Generated by Django 2.2.1 on 2019-06-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('heartrate', models.FloatField(blank=True, null=True)),
                ('emg', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(default=25)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default='Male')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('heartrate', models.FloatField(blank=True, null=True)),
                ('emg', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Patient')),
            ],
        ),
    ]
